apiVersion: v1
kind: Secret
metadata:
  name: immich-db-user
  namespace: immich
type: kubernetes.io/basic-auth
stringData:
  username: immich
  password: immich

---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich-database
  namespace: immich
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  instances: 1

  imageName: ghcr.io/tensorchord/cloudnative-vectorchord:16.9-0.4.3

  storage:
    size: 1Gi

  postgresql:
    shared_preload_libraries:
      - "vchord.so"

  bootstrap:
    initdb:
      database: immich
      owner: immich
      secret:
        name: immich-db-user

      postInitApplicationSQL:
        - CREATE EXTENSION vchord CASCADE;
        - CREATE EXTENSION earthdistance CASCADE;
