apiVersion: v1
stringData:
  username: immich
  password: immich
kind: Secret
metadata:
  name: immich-db-secret
type: kubernetes.io/basic-auth

---

apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich-database
  namespace: cloudnative-pg
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  instances: 1

  imageName: ghcr.io/tensorchord/cloudnative-vectorchord:16.9-0.4.3

  storage:
    size: 8Gi

  postgresql:
    shared_preload_libraries:
      - "vchord.so"

  bootstrap:
    initdb:
      database: immich
      owner: immich
      secret:
        name: immich-db-secret
      postInitApplicationSQL:
        - CREATE EXTENSION vchord CASCADE;
        - CREATE EXTENSION earthdistance CASCADE;

  enableSuperuserAccess: true
