apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openwebui
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/vexdev/vex-k8s.git
    path: charts/openwebui
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: openwebui
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
